name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: swip-implant-ecommerce
      PROJECT_ID: taki-41b6b
      BUCKET_NAME: swipall
      ARTIFACT: us-central1-docker.pkg.dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_GCP }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker ${{ env.ARTIFACT }} --quiet

    - name: Build Docker Image
      run: |-
        docker build \
          --build-arg NEXT_PUBLIC_SWIPALL_SHOP_API_URL="${{ secrets.SWIPALL_SHOP_API_URL }}" \
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.ARTIFACT }}/${{ env.PROJECT_ID }}/${{ env.BUCKET_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.ARTIFACT }}/${{ env.PROJECT_ID }}/${{ env.BUCKET_NAME }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.ARTIFACT }}/${{ env.PROJECT_ID }}/${{ env.BUCKET_NAME }}/${{ env.IMAGE_NAME }} --all-tags

  deploy-new-version:
    needs: build-push-gcr
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY_GCP_VM }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Update image in VM'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'aurus-paola'
          zone: 'us-central1-c'
          user: 'dante'
          ssh_private_key: '${{ secrets.PRIVATE_KEY }}'
          command: >
                sh /home/dante/swip-implant-ecommerce/deploy.sh
