name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: swip-implant-ecommerce
      PROJECT_ID: taki-41b6b
      SERVICE: ""
      BUCKET_NAME: swipall
      ARTIFACT: us-central1-docker.pkg.dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY_GCP }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker $ARTIFACT --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:${{ github.sha }} $ARTIFACT/$PROJECT_ID/$BUCKET_NAME/$IMAGE_NAME:${{ github.sha }}
        docker push $ARTIFACT/$PROJECT_ID/$BUCKET_NAME/$IMAGE_NAME:${{ github.sha }}